# The URL the site will be built for
base_url = "https://naveedpash.github.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# Theme
theme = 'zola.386'

taxonomies = [
  {name="categories", feed=true},
  {name="tags", feed=true},
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
author = 'Naveed Aman Pasha'
year = 2021
theme_color = '#000000'

### THIRD PARTY
google_analytics = "G-S18PPRL7TN"
disqus = "naveedpash"

### SOCIAL MEDIA
#image = "https://raw.githubusercontent.com/lopes/zola.386/master/screenshot.png"
twitter_user = "nap_attack"
github_user = "naveedpash"

keywords = 'zola, surgeon, general surgery, health informatics, rust, network programming, rust embedded'

zola386_menu = [
  {path="/", name="Home"},
  {path="categories", name="Categories"},
  {path="tags", name="Tags"},
  {path="about", name="About"},
]

### I18N WORDS
label_tags = "Tags"
label_tag = "Tag"
label_categories = "Categories"
label_category = "Category"
label_author = "Author"
label_date = "Date"
label_taxonomy = "Taxonomy"
label_reading = "Reading time"
label_read_more = "Read more"
